# Name of your application. Used to uniquely configure containers.
service: insta_clean

# Name of the container image.
image: toatoko/insta_clean

# Deploy to these servers.
servers:
  web:
    - 13.60.9.221

proxy:
  ssl: true
  host: blog.test.website

registry:
  username: toatoko
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_DB_PASSWORD
  # clear:
  #   # Set number of cores available to the application on each server (default: 1).
  #   WEB_CONCURRENCY: 2

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - "insta_clean_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - /home/toko/Downloads/mamamia.pem

# Use accessory services (secrets come from .kamal/secrets).
accessories:
  insta_clean_production:
    image: postgres:17.5
    host: 13.60.9.221
    port: 5432:5432
    env:
      clear:
        POSTGRES_USER: insta_clean
        POSTGRES_DB: insta_clean_production
        POSTGRES_PASSWORD: $KAMAL_DB_PASSWORD
    volumes:
      - /data/insta_clean/postgres:/var/lib/postgresql/data
    options:
      health-cmd: "pg_isready -U $POSTGRES_USER"
